name: libris_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.9

  # Firebase
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2

  # UI
  cupertino_icons: ^1.0.2
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  icons_launcher: ^3.0.2
  flutter_slidable: ^4.0.1
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
