// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'package:libris_app/config/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: AppConfig.androidApiKey,
    appId: AppConfig.androidAppId,
    messagingSenderId: AppConfig.androidMessagingSenderId,
    projectId: AppConfig.androidProjectId,
    storageBucket: AppConfig.androidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: AppConfig.iosApiKey,
    appId: AppConfig.iosAppId,
    messagingSenderId: AppConfig.iosMessagingSenderId,
    projectId: AppConfig.iosProjectId,
    storageBucket: AppConfig.iosStorageBucket,
    iosBundleId: AppConfig.iosBundleId,
  );
}
